"""Codex provider implementation."""

from __future__ import annotations

from dekk.skills.constants import (
    AGENTS_MD,
    AGENTS_REFERENCE_MD,
    CLAUDE_MCP_DIR,
    CODEX_AGENT_YAML,
    CODEX_AGENTS_DIR,
    MCP_COMMAND,
    MCP_SERVER_SUFFIX,
    PLUGIN_KEY_DESCRIPTION,
    PLUGIN_KEY_MCP,
    PLUGIN_KEY_NAME,
    PLUGIN_KEY_SERVER,
    PLUGIN_KEY_TOOLS,
    PLUGIN_KEY_VERSION,
    TARGET_CODEX,
)
from dekk.skills.discovery import SkillDefinition
from dekk.skills.providers.base import AgentContext, DekkAgent
from dekk.skills.providers.shared import remove_file, remove_tree


def render_codex_skill(skill: SkillDefinition) -> str:
    """Render a skill in Codex format with minimal frontmatter."""
    return (
        "---\n"
        f"name: {skill.name}\n"
        f"description: {skill.description}\n"
        "---\n\n"
        f"{skill.body.lstrip()}"
    )


class CodexAgent(DekkAgent):
    """Codex target generation."""

    target = TARGET_CODEX

    def generate(self, context: AgentContext) -> list[str]:
        agents_ref = context.source_dir / AGENTS_REFERENCE_MD
        content = (
            agents_ref.read_text(encoding="utf-8")
            if agents_ref.is_file()
            else context.project_content
        )
        agents_md = context.project_root / AGENTS_MD
        agents_md.write_text(content, encoding="utf-8")
        results = [AGENTS_MD]

        if context.enrichment and context.enrichment.mcp_tools:
            results.extend(self._generate_agent_yaml(context))

        return results

    def _generate_agent_yaml(self, context: AgentContext) -> list[str]:
        """Generate ``agents/openai.yaml`` with MCP server reference."""
        enrichment = context.enrichment
        assert enrichment is not None

        agents_dir = context.project_root / CODEX_AGENTS_DIR
        agents_dir.mkdir(parents=True, exist_ok=True)

        server_script = (
            f"{context.source_dir_name}/{CLAUDE_MCP_DIR}/"
            f"{enrichment.project_name}{MCP_SERVER_SUFFIX}"
        )

        # Build YAML content manually to avoid pyyaml dependency.
        tools_section = "\n".join(
            f"    - {PLUGIN_KEY_NAME}: {t.name}\n"
            f"      {PLUGIN_KEY_DESCRIPTION}: {t.description}"
            for t in enrichment.mcp_tools
        )
        yaml_content = (
            f"# Auto-generated by dekk — {enrichment.project_name} agent config\n"
            f"{PLUGIN_KEY_NAME}: {enrichment.project_name}\n"
            f"{PLUGIN_KEY_DESCRIPTION}: "
            f"{enrichment.project_description or enrichment.project_name}\n"
            f"{PLUGIN_KEY_VERSION}: {enrichment.version}\n"
            f"{PLUGIN_KEY_MCP}:\n"
            f"  {PLUGIN_KEY_SERVER}: {server_script}\n"
            f"  command: {MCP_COMMAND}\n"
            f"  {PLUGIN_KEY_TOOLS}:\n"
            f"{tools_section}\n"
        )

        yaml_path = agents_dir / CODEX_AGENT_YAML
        yaml_path.write_text(yaml_content, encoding="utf-8")
        return [f"{CODEX_AGENTS_DIR}/{CODEX_AGENT_YAML}"]

    def clean(self, context: AgentContext) -> list[str]:
        removed = remove_file(context.project_root / AGENTS_MD, AGENTS_MD)
        removed.extend(
            remove_tree(
                context.project_root / CODEX_AGENTS_DIR,
                f"{CODEX_AGENTS_DIR}/",
            )
        )
        return removed


__all__ = ["CodexAgent", "render_codex_skill"]
